import Link from "next/link";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArrowDown, ArrowRight, Check } from "lucide-react";
import { Header, Footer } from "@/components/site-chrome";
import { BookingWidget } from "@/components/booking-widget";
import { ServiceCard } from "@/components/service-card";
import { categories, getCategory, getServiceFromPrice } from "@/lib/services";
import { categoryComparisonFeatures } from "@/lib/category-presentation";
import { JsonLd } from "@/components/json-ld";
import { categoryDescription, categoryTitle, localBusinessSchema, siteUrl } from "@/lib/seo";
import { getLowestPackagePrice } from "@/lib/booking-services";

export function generateStaticParams() { return categories.map((category) => ({ slug: category.slug })) }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params; const category = getCategory(slug); if (!category) return {};
  const title = categoryTitle(category); const description = categoryDescription(category); const url = `/category/${category.slug}`;
  return { title, description, alternates: { canonical: url }, openGraph: { title, description, url, siteName: "Auto Opulence", locale: "en_GB", type: "website", images: [{ url: category.image, width: 1200, height: 800, alt: `${category.title} services at Auto Opulence in Norwich` }] }, twitter: { card: "summary_large_image", title, description, images: [category.image] } };
}

export default async function CategoryPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const category = getCategory(slug); if (!category) notFound();
  const pageUrl = `${siteUrl}/category/${category.slug}`;
  const schema = { "@context": "https://schema.org", "@graph": [localBusinessSchema, { "@type": "CollectionPage", "@id": `${pageUrl}/#webpage`, url: pageUrl, name: categoryTitle(category), description: categoryDescription(category), about: { "@id": `${siteUrl}/#business` }, mainEntity: { "@id": `${pageUrl}/#services` }, primaryImageOfPage: { "@id": `${pageUrl}/#primaryimage` }, inLanguage: "en-GB" }, { "@type": "ImageObject", "@id": `${pageUrl}/#primaryimage`, contentUrl: `${siteUrl}${category.image}`, caption: `${category.title} services at Auto Opulence in Norwich` }, { "@type": "ItemList", "@id": `${pageUrl}/#services`, name: `${category.title} services`, numberOfItems: category.services.length, itemListElement: category.services.map((service, index) => ({ "@type": "ListItem", position: index + 1, name: service.title, url: `${siteUrl}/service/${service.slug}` })) }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteUrl }, { "@type": "ListItem", position: 2, name: category.title, item: pageUrl }] }] };
  const otherCategories = categories.filter((item) => item.slug !== category.slug);
  const mainServices = category.services.filter((service) => !service.isAddOn);
  const additionalServices = category.services.filter((service) => service.isAddOn);
  const comparisonFeatures = categoryComparisonFeatures[category.slug] ?? [];
  return <><JsonLd data={schema} /><Header /><main>
    <section className="service-hero category-service-hero" style={{"--category-accent": category.accent} as React.CSSProperties}><img className="service-hero-image" src={category.image} alt={`${category.title} services at Auto Opulence in Norwich`} width="1200" height="800" fetchPriority="high" decoding="async" /><div className="service-hero-shade" /><div className="shell service-hero-content"><div className="service-hero-copy"><p className="kicker">{category.eyebrow} · Norwich</p><h1>{category.title}</h1><p>{category.intro}</p><div className="category-hero-actions"><a href="#treatments" className="button">Choose a treatment <ArrowDown size={18} /></a><a href="#compare-services" className="category-hero-text-link">Compare services <ArrowDown size={17} /></a></div></div><div className="service-hero-proof category-hero-proof"><strong>{category.services.length} service options</strong><span>{additionalServices.length > 0 ? `${mainServices.length} main services · ${additionalServices.length} additional services` : "Clear inclusions and pricing for every option"}</span></div></div></section>
    <section className="section shell" id="treatments"><div className="section-heading compact"><div><p className="kicker">Select a sub service</p><h2>Find the right level of care.</h2></div><p>Choose a main service first, then add any optional treatments. Open a service to compare vehicle sizes, inclusions and prices.</p></div>
      <header className="service-group-heading"><p className="kicker">Your base booking</p><h3>Main services</h3><p>These services can be booked as the main treatment for your vehicle.</p></header>
      <div className="service-list visual-service-grid">{mainServices.map((service, index) => <ServiceCard key={service.slug} category={category} service={service} index={index} />)}</div>
      {additionalServices.length > 0 && <><header className="service-group-heading additional"><p className="kicker">Optional treatments</p><h3>Additional services</h3><p>These prices are additional costs added to a suitable main service booking.</p></header><div className="service-list visual-service-grid additional-service-list">{additionalServices.map((service, index) => <ServiceCard key={service.slug} category={category} service={service} index={mainServices.length + index} />)}</div></>}
      <section className="service-comparison comparison-grid" id="compare-services" aria-labelledby="service-comparison-title"><div className="service-comparison-heading"><div><p className="kicker">Service comparison</p><h2 id="service-comparison-title">See what is included.</h2></div><p>Compare every {category.title.toLowerCase()} option in one chart. A tick shows that the feature is included within that service.</p></div><div className="comparison-chart-wrap"><table className="comparison-chart"><caption className="sr-only">Included-feature comparison for {category.title.toLowerCase()} services</caption><thead><tr><th scope="col">Service</th>{comparisonFeatures.map((feature) => <th scope="col" key={feature.label}><span title={feature.label}>{feature.label}</span></th>)}</tr></thead><tbody>{category.services.map((service) => { const packageFrom = getLowestPackagePrice(service.slug); return <tr className={service.isAddOn ? "is-add-on" : ""} key={service.slug}><th scope="row"><Link href={`/service/${service.slug}`}><span>{service.title}</span><small>{packageFrom === undefined ? `${service.isAddOn ? "Additional cost" : "Main service"} · ${getServiceFromPrice(service)}` : `From ${getServiceFromPrice(service)} · Package from £${packageFrom}/visit`}</small></Link></th>{comparisonFeatures.map((feature) => { const included = feature.includedFor.includes(service.slug); return <td key={feature.label}>{included ? <span className="chart-tick"><Check size={17} strokeWidth={3} /><span className="sr-only">Included</span></span> : <span className="chart-empty" aria-label="Not included">—</span>}</td>; })}</tr>; })}</tbody></table></div><p className="service-comparison-note">{additionalServices.length > 0 ? "Additional services are charged on top of a suitable main service. " : ""}Select a service name for its full description and vehicle-size pricing.</p></section>
      <article className="category-seo-copy"><h2>{category.title} in Norwich, Norfolk</h2><p>{category.intro} Every option is organised by vehicle size, making it easier to choose suitable care for compact cars, family vehicles, estates, SUVs, 4x4s and vans.</p><p>Build a complete vehicle-care plan by combining this service with {otherCategories.map((item, index) => <span key={item.slug}>{index > 0 && (index === otherCategories.length - 1 ? " or " : ", ")}<Link href={`/category/${item.slug}`}>{item.title.toLowerCase()}</Link></span>)}. Each treatment page explains what is included, answers common questions and links directly to the booking section.</p></article>
    </section>
    <section className="booking-section shell"><BookingWidget initialCategory={category.slug} /></section>
    <nav className="next-category shell" aria-label="Related service categories"><p>Need something different?</p><div>{categories.filter((item) => item.slug !== category.slug).map((item) => <Link key={item.slug} href={`/category/${item.slug}`}>{item.title}<ArrowRight size={16} /></Link>)}</div></nav>
  </main><Footer /></>;
}
