// Step 1 of the static export: bundles source/ (the Next.js project) twice with esbuild, without Next itself.
//   gen/server.mjs     – renders every page to HTML in Node (used by render.mjs)
//   gen/client/*.js    – the browser bundle; one small chunk per page, which hydrates the static HTML
// Next-only modules (next/link, next/script, lucide-react, the Radix Select, the day picker) are swapped for
// the small stand-ins in shims/.
import * as esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { staticPages, dynamicPages } from "./pages.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SOURCE = path.resolve(HERE, "../../source");
const SHIMS = path.join(HERE, "shims");
const GEN = path.join(HERE, "gen");
const NODE_PATHS = [process.env.NODE_PATHS || path.join(HERE, "node_modules")];
fs.rmSync(GEN, { recursive: true, force: true });
fs.mkdirSync(GEN, { recursive: true });

const walk = (d) => fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)]);
const srcFiles = ["app", "components", "lib", "hooks"].flatMap((d) => walk(path.join(SOURCE, d))).filter((f) => /\.(tsx?|jsx?)$/.test(f));

// ---- lucide-react → the same icons from react-icons (Lucide set), with explicit named exports
const names = new Set();
for (const f of srcFiles) for (const m of fs.readFileSync(f, "utf8").matchAll(/import\s*\{([^}]+)\}\s*from\s*["']lucide-react["']/g))
  m[1].split(",").map((s) => s.replace(/\btype\s+/, "").trim().split(/\s+as\s+/)[0]).filter(Boolean).forEach((n) => names.add(n));
const lu = (await import(path.join(NODE_PATHS[0], "react-icons/lu/index.mjs")));
const renamed = { CheckCircle2: ["CircleCheck", "CircleCheckBig"], MoreHorizontal: ["Ellipsis"], Loader2: ["LoaderCircle"] };
const pairs = [...names].sort().map((n) => {
  const base = n.replace(/Icon$/, "");
  const hit = [...(renamed[base] || []), base].find((c) => lu["Lu" + c]);
  if (!hit) console.warn("icon not found, using a circle:", n);
  return [n, "Lu" + (hit || "Circle")];
});
fs.writeFileSync(path.join(GEN, "lucide.tsx"), `// @ts-nocheck\n// GENERATED by build.mjs\nimport { ${[...new Set(pairs.map((p) => p[1]))].join(", ")} } from "react-icons/lu";\n` +
  `const make = (C) => function Icon({ size, strokeWidth, absoluteStrokeWidth, ...rest }) { return <C {...rest} size={size ?? 24} strokeWidth={strokeWidth} />; };\n` +
  pairs.map(([n, c]) => `export const ${n} = make(${c});`).join("\n") + "\n");

// ---- entry files generated from pages.mjs
const imp = (p) => JSON.stringify("@/" + p);
fs.writeFileSync(path.join(GEN, "server-entry.tsx"), `// @ts-nocheck\n// GENERATED by build.mjs
import { renderToString } from "react-dom/server";
import { Shell, resolveRoute, renderPage } from "../shell";
export { renderToString, Shell };
export { createElement } from "react";
export * as layout from "@/app/layout";
export { default as sitemap } from "@/app/sitemap";
export { default as robots } from "@/app/robots";
export { Header, Footer } from "@/components/site-chrome";
${[...Object.values(staticPages), ...Object.values(dynamicPages)].map((v, i) => `import * as m${i} from ${imp(v)};`).join("\n")}
const mods = [${[...Object.values(staticPages), ...Object.values(dynamicPages)].map((_, i) => "m" + i).join(", ")}];
const staticPages = ${JSON.stringify(Object.fromEntries(Object.keys(staticPages).map((k, i) => [k, i])))};
const dynamicPages = ${JSON.stringify(Object.fromEntries(Object.keys(dynamicPages).map((k, i) => [k, i + Object.keys(staticPages).length])))};
export async function allRoutes() {
  const out = Object.keys(staticPages);
  for (const [base, i] of Object.entries(dynamicPages)) for (const p of await mods[i].generateStaticParams()) out.push(base + "/" + p.slug);
  return out;
}
function pick(route) { const r = resolveRoute(route, staticPages, dynamicPages); return r && { mod: mods[r.dynamic ? dynamicPages[r.key] : staticPages[r.key]], params: r.params }; }
export async function pageElement(route) { const { mod, params } = pick(route); return <Shell>{await renderPage(mod, params)}</Shell>; }
export async function pageMetadata(route) {
  const { mod, params } = pick(route);
  return mod.generateMetadata ? await mod.generateMetadata({ params: Promise.resolve(params) }) : (mod.metadata || {});
}
`);
fs.writeFileSync(path.join(GEN, "client-entry.tsx"), `// @ts-nocheck\n// GENERATED by build.mjs
import { hydrateRoot } from "react-dom/client";
import { Shell, resolveRoute, renderPage } from "../shell";
const staticPages = {
${Object.entries(staticPages).map(([k, v]) => `  ${JSON.stringify(k)}: () => import(${imp(v)}),`).join("\n")}
};
const dynamicPages = {
${Object.entries(dynamicPages).map(([k, v]) => `  ${JSON.stringify(k)}: () => import(${imp(v)}),`).join("\n")}
};
// Some browsers block storage (private mode); give the page an in-memory stand-in so it still works.
try { window.localStorage.getItem("ao"); } catch {
  const mem = new Map();
  const store = { getItem: (k) => mem.has(k) ? mem.get(k) : null, setItem: (k, v) => mem.set(k, String(v)), removeItem: (k) => mem.delete(k), clear: () => mem.clear(), key: (i) => [...mem.keys()][i] ?? null, get length() { return mem.size; } };
  try { Object.defineProperty(window, "localStorage", { value: store, configurable: true }); Object.defineProperty(window, "sessionStorage", { value: store, configurable: true }); } catch {}
}
const root = document.getElementById("root");
const route = root?.dataset.route;
globalThis.__AO_ROUTE = route;
const r = route && resolveRoute(route, staticPages, dynamicPages);
if (r) (r.dynamic ? dynamicPages[r.key] : staticPages[r.key])()
  .then((mod) => renderPage(mod, r.params))
  .then((el) => hydrateRoot(root, <Shell>{el}</Shell>, { onRecoverableError: () => {} }));
`);

// ---- bundling
const shimFor = { "next/link": "next-link.tsx", "next/navigation": "next-navigation.ts", "next/script": "next-script.tsx", "next/headers": "next-headers.ts", "@/components/ui/select": "select.tsx", "@/components/ui/calendar": "calendar.tsx" };
const shims = { name: "shims", setup(b) {
  b.onResolve({ filter: /.*/ }, (a) => {
    if (shimFor[a.path]) return { path: path.join(SHIMS, shimFor[a.path]) };
    if (a.path === "lucide-react") return { path: path.join(GEN, "lucide.tsx") };
    if (a.path.endsWith(".css")) return { path: a.path, namespace: "empty" };
  });
  b.onLoad({ filter: /.*/, namespace: "empty" }, () => ({ contents: "", loader: "js" }));
} };
const common = {
  bundle: true, jsx: "automatic", tsconfig: path.join(SOURCE, "tsconfig.json"), nodePaths: NODE_PATHS, plugins: [shims],
  absWorkingDir: SOURCE, logLevel: "warning", define: { "process.env.NODE_ENV": '"production"' },
};
await esbuild.build({
  ...common, entryPoints: [path.join(GEN, "server-entry.tsx")], platform: "node", format: "esm", outfile: path.join(GEN, "server.mjs"),
  banner: { js: 'import { createRequire as __cr } from "node:module"; const require = __cr(import.meta.url);' },
});
await esbuild.build({
  ...common, entryPoints: { app: path.join(GEN, "client-entry.tsx") }, platform: "browser", format: "esm", splitting: true, minify: true,
  outdir: path.join(GEN, "client"), chunkNames: "chunks/[name]-[hash]", define: { ...common.define, "process.env": "{}" },
});
console.log("bundled", pairs.length, "icons,", Object.keys(staticPages).length, "static and", Object.keys(dynamicPages).length, "dynamic page types");
