// Bundles the Worker into worker/dist/index.js (committed, and uploaded as-is by `wrangler deploy`).
// Node built-ins (node:crypto, node:path) are left for Cloudflare's nodejs_compat; nodemailer, node:fs/promises
// and the env helper are swapped for the Worker versions in src/shims.
import * as esbuild from "esbuild";
import path from "node:path";
import { fileURLToPath } from "node:url";
const HERE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../worker");
const SOURCE = path.resolve(HERE, "../source");
const NODE_PATHS = [process.env.NODE_PATHS || path.resolve(HERE, "../tools/static-export/node_modules")];
const swap = { "nodemailer": "nodemailer.ts", "node:fs/promises": "fs-promises.ts", "fs/promises": "fs-promises.ts", "@/lib/runtime-env": "runtime-env.ts" };
await esbuild.build({
  entryPoints: [path.join(HERE, "src/index.ts")], outfile: path.join(HERE, "dist/index.js"),
  bundle: true, format: "esm", platform: "neutral", target: "es2022", mainFields: ["module", "main"], conditions: ["workerd", "worker", "browser"],
  tsconfig: path.join(SOURCE, "tsconfig.json"), nodePaths: NODE_PATHS, external: ["node:*"], logLevel: "warning",
  banner: { js: "// GENERATED by tools/static-export/build-worker.mjs from worker/src and source/ — do not edit by hand." },
  plugins: [{ name: "swap", setup(b) {
    b.onResolve({ filter: /.*/ }, (a) => swap[a.path] ? { path: path.join(HERE, "src/shims", swap[a.path]) } : undefined);
  } }],
});
console.log("worker bundled");
