import type { Metadata } from "next";
import Link from "next/link";
import { Footer, Header } from "@/components/site-chrome";
import { JsonLd } from "@/components/json-ld";
import { siteUrl } from "@/lib/seo";

const title = "Privacy Policy | Auto Opulence";
const description = "How Auto Opulence collects, uses, shares and protects personal information when you enquire, book or use our website.";

export const metadata: Metadata = {
  title,
  description,
  alternates: { canonical: "/privacy" },
  openGraph: { title, description, url: "/privacy", siteName: "Auto Opulence", locale: "en_GB", type: "website" },
  twitter: { card: "summary", title, description },
};

export default function PrivacyPage() {
  const pageUrl = `${siteUrl}/privacy`;
  const schema = { "@context": "https://schema.org", "@type": "WebPage", "@id": `${pageUrl}/#webpage`, url: pageUrl, name: title, description, isPartOf: { "@id": `${siteUrl}/#website` }, dateModified: "2026-09-22", inLanguage: "en-GB" };
  return <><JsonLd data={schema} /><Header /><main className="policy-page">
    <header className="policy-hero"><div className="shell"><p className="kicker">Legal information</p><h1>Privacy Policy</h1><p>How we use and protect your personal information when you contact us, book vehicle care or use an Auto Opulence customer account.</p><small>Last updated: 22 September 2026</small></div></header>
    <div className="policy-layout shell">
      <aside><strong>On this page</strong><nav aria-label="Privacy policy sections"><a href="#who-we-are">Who we are</a><a href="#information">Information we collect</a><a href="#use">How we use it</a><a href="#sharing">Who we share it with</a><a href="#retention">How long we keep it</a><a href="#rights">Your rights</a><a href="#contact">Contact and complaints</a></nav></aside>
      <article className="policy-content">
        <section id="who-we-are"><h2>1. Who we are</h2><p>Auto Opulence provides vehicle valeting, washing, polishing, ceramic coating and valet bay hire services. For personal information collected through this website and our direct customer relationships, Auto Opulence is the data controller.</p><address><strong>Auto Opulence</strong><br />Unit 7 Consensus House<br />St Faiths Road<br />Norwich, Norfolk, NR6 7BW<br /><a href="mailto:valeting@autoopulence.co.uk">valeting@autoopulence.co.uk</a><br /><a href="tel:03300536925">0330 053 6925</a></address></section>
        <section id="information"><h2>2. Information we collect</h2><p>Depending on how you use our services, we may collect:</p><ul><li>your name, email address, telephone number and postal address;</li><li>booking, appointment, package, invoice and payment-status information;</li><li>customer-account details and account activity held through our booking provider;</li><li>information about your vehicle, its condition and the services you request;</li><li>messages, enquiry details, uploaded photographs or documents, and correspondence with our team;</li><li>postcode information used to help complete an address;</li><li>technical and usage information, such as device, browser, approximate location, pages viewed and referral source, where you consent to analytics;</li><li>security records needed to protect the website, customer accounts and booking process.</li></ul><p>Card details are entered into the secure payment service made available through our booking platform and Stripe. Auto Opulence does not receive or store your complete payment-card number through this website.</p></section>
        <section id="use"><h2>3. How and why we use personal information</h2><div className="policy-table-wrap"><table><thead><tr><th>Purpose</th><th>Typical information</th><th>Lawful basis</th></tr></thead><tbody><tr><td>Answer enquiries and prepare service recommendations</td><td>Contact, vehicle and message details</td><td>Steps requested before a contract and our legitimate interests in responding to customers</td></tr><tr><td>Create and manage bookings, packages and customer accounts</td><td>Contact, account, appointment and vehicle details</td><td>Contract and steps requested before a contract</td></tr><tr><td>Take payment and maintain financial records</td><td>Invoice, payment status and transaction references</td><td>Contract and legal obligations</td></tr><tr><td>Provide service updates and customer support</td><td>Contact, booking and correspondence details</td><td>Contract and legitimate interests in customer service</td></tr><tr><td>Protect the website and prevent misuse</td><td>Session, device, network and security information</td><td>Legitimate interests in security and fraud prevention</td></tr><tr><td>Measure website use with Google Analytics</td><td>Online identifiers and usage data</td><td>Your consent</td></tr></tbody></table></div><p>We do not use enquiry or booking consent as permission to send unrelated marketing. If we introduce optional email marketing, we will ask separately where consent is required and provide an easy way to unsubscribe.</p></section>
        <section id="sharing"><h2>4. Who we share information with</h2><p>We only share information where needed to operate the service, comply with law or protect our rights. Recipients may include:</p><ul><li><strong>our booking-platform provider</strong>, which provides appointment availability, bookings, packages and customer accounts;</li><li><strong>Stripe</strong>, for secure card payment;</li><li><strong>Ideal Postcodes</strong>, when you ask the website to look up an address;</li><li><strong>SendGrid and our email recipients</strong>, to deliver enquiry notifications and confirmations;</li><li><strong>EnquiryBot</strong>, which provides the website chat and enquiry launcher when you use that feature;</li><li><strong>Google Analytics</strong>, only after you accept analytics cookies;</li><li><strong>website hosting, security and technical service providers</strong> acting on our instructions;</li><li>professional advisers, insurers, regulators, courts, police or other authorities where necessary or legally required.</li></ul><p>Some providers may process information outside the UK. Where this happens, we expect an appropriate UK transfer safeguard to be used, such as an adequacy regulation or approved contractual protections. Providers also publish their own privacy information about how they handle data.</p></section>
        <section id="retention"><h2>5. How long we keep information</h2><p>We keep personal information only for as long as reasonably needed for the purpose collected and to meet legal, accounting, tax, insurance and dispute-resolution requirements.</p><ul><li>Enquiries that do not become a booking are normally reviewed and deleted within 24 months of the last meaningful contact.</li><li>Booking, invoice and payment records may be retained for up to six years after the relevant financial year or customer relationship where needed for legal and accounting purposes.</li><li>Customer-account and package information is retained while the account or package is active and then in line with our booking-platform settings and legal requirements.</li><li>Security logs and temporary booking-session information are kept for shorter operational periods.</li><li>Google Analytics retention is controlled through our Analytics settings and associated cookie lifetimes.</li></ul></section>
        <section id="rights"><h2>6. Your data-protection rights</h2><p>Depending on the circumstances, UK data-protection law may give you the right to:</p><ul><li>ask for a copy of your personal information;</li><li>ask us to correct inaccurate or incomplete information;</li><li>ask us to erase information;</li><li>ask us to restrict how information is used;</li><li>object to processing based on legitimate interests or to direct marketing;</li><li>receive certain information in a portable format;</li><li>withdraw consent at any time, without affecting earlier lawful processing.</li></ul><p>These rights are not absolute and exemptions may apply. We may ask for enough information to confirm your identity before responding.</p></section>
        <section><h2>7. Cookies and similar technology</h2><p>We use essential technology for secure booking sessions and temporary payment-return information. Google Analytics is loaded only if you accept analytics. Read the <Link href="/cookies">Cookie Policy</Link> or use “Cookie settings” in the footer to change your choice.</p></section>
        <section id="contact"><h2>8. Questions, requests and complaints</h2><p>Email <a href="mailto:valeting@autoopulence.co.uk">valeting@autoopulence.co.uk</a> or write to the address above to exercise a right or raise a privacy concern. Please contact us first so we have the opportunity to help.</p><p>You also have the right to complain to the UK Information Commissioner’s Office. Visit <a href="https://ico.org.uk/make-a-complaint/" target="_blank" rel="noopener noreferrer">ico.org.uk/make-a-complaint</a> for current guidance.</p></section>
        <section><h2>9. Changes to this policy</h2><p>We may update this policy when our services, providers or legal obligations change. The date at the top shows the latest revision.</p></section>
      </article>
    </div>
  </main><Footer /></>;
}
