import Link from "next/link";
import { ArrowRight, ShieldCheck, Sparkles } from "lucide-react";
import { Header, Footer } from "@/components/site-chrome";
import { BookingWidget } from "@/components/booking-widget";
import { EnquiryForm } from "@/components/enquiry-form";
import { HomeHeroCarousel } from "@/components/home-hero-carousel";
import { categories } from "@/lib/services";
import { JsonLd } from "@/components/json-ld";
import { localBusinessSchema, siteUrl } from "@/lib/seo";

export default function Home() {
  const homeSchema = { "@context": "https://schema.org", "@graph": [localBusinessSchema, { "@type": "WebSite", "@id": `${siteUrl}/#website`, url: siteUrl, name: "Auto Opulence", alternateName: ["Auto Opulence Norwich", "Auto Opulence Detailing"], publisher: { "@id": `${siteUrl}/#business` }, inLanguage: "en-GB" }, { "@type": "WebPage", "@id": `${siteUrl}/#webpage`, url: siteUrl, name: "Car Valeting & Detailing Norwich | Auto Opulence", isPartOf: { "@id": `${siteUrl}/#website` }, about: { "@id": `${siteUrl}/#business` }, inLanguage: "en-GB" }] };
  return <><JsonLd data={homeSchema} /><Header /><main>
    <HomeHeroCarousel />
    <section className="section shell home-services" id="services"><div className="section-heading"><div><p className="kicker">Choose your route</p><h2>Four ways to care for your vehicle.</h2></div><p>From a maintenance wash to complete interior care, paint correction or hiring the bay yourself.</p></div>
      <div className="category-grid">{categories.map((category, index) => <Link href={`/category/${category.slug}`} className="category-card" key={category.slug} style={{"--card-accent": category.accent} as React.CSSProperties}><div className="category-image"><img src={category.image} alt={`${category.title} services in Norwich`} width="1200" height="800" loading="lazy" decoding="async" /><span>0{index + 1}</span></div><div className="category-content"><p>{category.eyebrow}</p><h3>{category.title}</h3><span>Explore services <ArrowRight size={18} /></span></div></Link>)}</div>
    </section>
    <section className="graphics-care-promo"><div className="shell"><div className="section-heading"><div><p className="kicker">Vehicle graphics care</p><h2>Prepare properly. Protect the finished graphics.</h2></div><p>Specialist cleaning before installation and ceramic protection afterwards help vehicle graphics look their best and remain easier to maintain.</p></div><div className="graphics-care-grid"><article><figure><img src="/images/home-sections/pre-graphics-decontamination.webp" alt="White vehicle receiving clay-bar decontamination before graphics installation" width="1200" height="800" loading="lazy" decoding="async" /></figure><div className="graphics-care-content"><span>Before graphics</span><h3>Pre-installation clean & decontamination</h3><p>Remove road film, tar and bonded contamination before graphics or wrap installation. A properly prepared surface gives the installer a cleaner foundation to work with.</p><div className="graphics-care-actions"><Link href="/service/exterior-full-decontamination-wash-with-clay-bar">Book decontamination <ArrowRight size={17} /></Link><a href="https://racecargraphics.uk/" target="_blank" rel="noopener noreferrer">Discuss vehicle graphics ↗</a></div></div></article><article><figure><img src="/images/home-sections/wrap-ceramic-protection.webp" alt="Ceramic protection applied to a blue wrapped performance vehicle" width="1200" height="800" loading="lazy" decoding="async" /></figure><div className="graphics-care-content"><span>After graphics</span><h3>Wrap and graphics ceramic protection</h3><p>Add a suitable ceramic coating after installation to improve water behaviour, simplify regular cleaning and help protect the appearance of vinyl graphics and vehicle wraps.</p><div className="graphics-care-actions"><Link href="/contact">Request a protection quote <ArrowRight size={17} /></Link><a href="https://racecargraphics.uk/" target="_blank" rel="noopener noreferrer">Visit Race Car Graphics ↗</a></div></div></article></div></div></section>
    <section className="booking-section shell home-booking"><BookingWidget /></section>
    <section className="service-enquiry-section"><div className="shell service-enquiry-grid"><aside className="service-enquiry-intro"><p className="kicker">Service enquiry</p><h2>Not sure what your vehicle needs?</h2><p>Send the team a few details and we’ll help you choose between valeting, washing, paint correction, ceramic protection or valet bay hire.</p><ul><li>Advice based on your vehicle and its condition</li><li>Help choosing the correct vehicle size</li><li>Options for public, trade and business customers</li></ul></aside><EnquiryForm /></div></section>
    <article className="seo-overview shell"><header><p className="kicker">Professional vehicle care in Norwich</p><h2>Cleaning, correction and detailing under one roof.</h2></header><div><p>Keep your vehicle clean, comfortable and well presented with <Link href="/category/vehicle-valeting">professional vehicle valeting in Norwich</Link>. Choose a complete interior and exterior valet, deep interior cleaning, soft-top care or exterior trim rejuvenation.</p><p>For regular maintenance, explore our <Link href="/category/vehicle-washing">hand car washing services</Link>. If the paint needs greater clarity and gloss, compare <Link href="/category/vehicle-polishing">machine polishing, paint correction and ceramic coating</Link> packages. Prefer to complete the work yourself? Our <Link href="/category/valet-bay-hire">valet bay hire in Norwich</Link> provides an indoor workspace with specialist equipment for public and trade users.</p></div></article>
    <article className="facility-feature shell"><figure><img src="/images/home-sections/indoor-detailing-facility.webp" alt="Bright indoor vehicle detailing studio with spotless-water equipment and professional wash facilities" width="2000" height="750" loading="lazy" decoding="async" /></figure><div className="facility-feature-content"><p className="kicker">Built for careful work</p><h2>A professional indoor space, whatever the weather.</h2><p>Our Norwich facility brings inspection lighting, an indoor wash area, professional equipment and spotless water together in one controlled environment.</p><div><Link className="button" href="/about">Explore our facility <ArrowRight size={18} /></Link><Link className="inline-link" href="/category/valet-bay-hire">Hire the bay <ArrowRight size={17} /></Link></div></div></article>
    <section className="group-network shell"><div className="section-heading compact"><div><p className="kicker">Part of a wider creative group</p><h2>More ways to present your vehicle and business.</h2></div></div><div className="group-network-grid"><a href="https://racecargraphics.uk/" target="_blank" rel="noopener noreferrer"><div className="group-network-logo"><img src="/images/brands/race-car-graphics-logo.png" alt="Race Car Graphics UK" loading="lazy" /></div><span>Vehicle graphics & wrapping</span><h3>Race Car Graphics</h3><p>Vehicle graphics, van liveries, motorsport graphics, colour change wraps and specialist finishes from the Norwich team.</p><strong>Explore Race Car Graphics <ArrowRight size={17} /></strong></a><a href="https://broadlanddigital.co.uk/" target="_blank" rel="noopener noreferrer"><div className="group-network-logo"><img src="https://racecargraphics.uk/img/logos/bd-logo.svg" alt="Broadland Digital" loading="lazy" /></div><span>Design, print, web & signage</span><h3>Broadland Digital</h3><p>In-house design, commercial print, signage and website development for Norfolk businesses.</p><strong>Explore Broadland Digital <ArrowRight size={17} /></strong></a></div></section>
    <nav className="pathway-section shell" aria-label="Explore Auto Opulence resources"><Link href="/locations"><span>01 · Local service areas</span><h2>Find vehicle care near you.</h2><p>Plan a visit from Norwich and surrounding Norfolk towns.</p><strong>View locations <ArrowRight size={17} /></strong></Link><Link href="/business-sectors"><span>02 · For business</span><h2>Protect your professional image.</h2><p>Explore fleet, dealership, taxi, garage and trade solutions.</p><strong>View business sectors <ArrowRight size={17} /></strong></Link><Link href="/guides"><span>03 · Help & advice</span><h2>Choose the right treatment.</h2><p>Compare vehicle sizes, polishing stages and care options.</p><strong>Read the guides <ArrowRight size={17} /></strong></Link></nav>
    <section className="proof-section"><div className="shell proof-grid"><div><p className="kicker">The Auto Opulence standard</p><h2>Considered care, not a conveyor-belt clean.</h2></div><div className="proof-item"><Sparkles /><h3>Right treatment</h3><p>Every booking starts with the service and vehicle size, so the work can be planned properly.</p></div><div className="proof-item"><ShieldCheck /><h3>Safe methods</h3><p>Surface-appropriate products and controlled processes protect paint, trim and interior materials.</p></div></div></section>
  </main><Footer /></>;
}
