import Link from "next/link";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, CarFront, Check, Quote, Star } from "lucide-react";
import { Header, Footer } from "@/components/site-chrome";
import { BookingWidget } from "@/components/booking-widget";
import { categories, getService, getServiceFromPrice, getServicePrices, sizeOptions } from "@/lib/services";
import { JsonLd } from "@/components/json-ld";
import { localBusinessSchema, serviceDescription, serviceTitle, siteUrl } from "@/lib/seo";
import { getServiceCardImage, getServiceImageAlt } from "@/lib/category-presentation";
import { guides } from "@/lib/guides";
import { bookingPackages, getLowestPackagePrice, sizeLabels, type VehicleSize } from "@/lib/booking-services";

export function generateStaticParams() { return categories.flatMap((category) => category.services.map((service) => ({ slug: service.slug }))) }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params; const result = getService(slug); if (!result) return {};
  const title = serviceTitle(result.service); const description = serviceDescription(result.service); const url = `/service/${result.service.slug}`;
  const image = getServiceCardImage(result.service.slug, result.category.image);
  const imageAlt = getServiceImageAlt(result.service.slug, `${result.service.title} service at Auto Opulence in Norwich`);
  return { title, description, alternates: { canonical: url }, openGraph: { title, description, url, siteName: "Auto Opulence", locale: "en_GB", type: "website", images: [{ url: `${siteUrl}${image}`, width: 1200, height: 800, alt: imageAlt }] }, twitter: { card: "summary_large_image", title, description, images: [image] } };
}

export default async function ServicePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const result = getService(slug); if (!result) notFound(); const { category, service } = result; const related = category.services.filter((item) => item.slug !== service.slug).slice(0, 3);
  const helpfulGuides = guides.filter((guide) => guide.relatedServiceSlugs.includes(service.slug)).slice(0, 3);
  const servicePackages = bookingPackages.filter((item) => item.siteServiceSlugs.includes(service.slug));
  const faqs = [
    service.isAddOn
      ? { question: `Is ${service.title} a standalone service?`, answer: `No. ${service.priceNote} Choose a suitable main service first and we will confirm the complete booking and total price.` }
      : { question: "How do I know which vehicle size to choose?", answer: "Small generally covers city cars, Medium covers saloons and family hatchbacks, Large covers estates and crossovers, and Extra Large covers large SUVs, 4x4s and vans. We will confirm it before the booking." },
    { question: "How long will the service take?", answer: "Timing depends on the selected treatment, vehicle size and current condition. We will provide an expected completion time when confirming your appointment." },
    { question: "Do you inspect the vehicle first?", answer: "Yes. We check the vehicle and discuss any areas needing extra attention before starting so expectations are clear." },
    { question: "Where is Auto Opulence based?", answer: "Auto Opulence is at Unit 7 Consensus House, St Faiths Road, Norwich, NR6 7BW." },
  ];
  const pageUrl = `${siteUrl}/service/${service.slug}`;
  const serviceImage = getServiceCardImage(service.slug, category.image);
  const serviceImageAlt = getServiceImageAlt(service.slug, `${service.title} service at Auto Opulence in Norwich`);
  const prices = getServicePrices(service);
  const fromPrice = getServiceFromPrice(service);
  const lowestPackagePrice = getLowestPackagePrice(service.slug);
  const packageOffers = servicePackages.flatMap((item) => sizeOptions.filter((size) => (item.totals?.[size.key] ?? item.prices[size.key]) !== undefined).map((size) => ({ "@type": "Offer", name: `${item.name} — ${size.name} vehicle`, price: (item.totals?.[size.key] ?? item.prices[size.key] as number).toFixed(2), priceCurrency: "GBP", availability: "https://schema.org/InStock", url: `${pageUrl}?type=valet&service=${service.slug}&package=${item.crmSlug}#book`, category: item.totals ? "Service package total" : "Service package rate", description: item.note ? `${item.term}. ${item.note}` : item.term })));
  const sizeOffers = sizeOptions.flatMap((size) => prices[size.key].display === "POA" ? [] : [{ "@type": "Offer", name: `${service.title} — ${size.name} vehicle`, price: prices[size.key].amount, priceCurrency: "GBP", availability: "https://schema.org/InStock", url: `${pageUrl}#sizes`, description: `${size.example}.${service.priceNote ? ` ${service.priceNote}` : ""}` }]);
  const offers = [...sizeOffers, ...packageOffers];
  const schema = { "@context": "https://schema.org", "@graph": [localBusinessSchema, { "@type": "WebPage", "@id": `${pageUrl}/#webpage`, url: pageUrl, name: serviceTitle(service), description: serviceDescription(service), about: { "@id": `${pageUrl}/#service` }, primaryImageOfPage: { "@id": `${pageUrl}/#primaryimage` }, inLanguage: "en-GB" }, { "@type": "ImageObject", "@id": `${pageUrl}/#primaryimage`, contentUrl: `${siteUrl}${serviceImage}`, caption: serviceImageAlt }, { "@type": "Service", "@id": `${pageUrl}/#service`, name: service.title, serviceType: service.title, category: service.isAddOn ? "Additional vehicle-care service" : "Main vehicle-care service", description: serviceDescription(service), url: pageUrl, image: { "@id": `${pageUrl}/#primaryimage` }, provider: { "@id": `${siteUrl}/#business` }, areaServed: [{ "@type": "City", name: "Norwich" }, { "@type": "AdministrativeArea", name: "Norfolk" }], ...(offers.length ? { offers } : {}) }, { "@type": "FAQPage", "@id": `${pageUrl}/#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteUrl }, { "@type": "ListItem", position: 2, name: category.title, item: `${siteUrl}/category/${category.slug}` }, { "@type": "ListItem", position: 3, name: service.title, item: pageUrl }] }] };
  const complementary = categories.filter((item) => item.slug !== category.slug).slice(0, 3);
  return <><JsonLd data={schema} /><Header /><main>
    <section className="service-hero"><img className="service-hero-image" src={serviceImage} alt={serviceImageAlt} /><div className="service-hero-shade" /><div className="shell service-hero-content"><Link href={`/category/${category.slug}`} className="back-link"><ArrowLeft size={17} /> {category.title}</Link><div className="service-hero-copy"><p className="kicker">{service.isAddOn ? "Additional service" : "Main service"} · Norwich</p><h1>{service.title}</h1><p>{service.short}</p><div className="campaign-price service-hero-price"><span>{fromPrice === "POA" ? "POA" : `${service.isAddOn ? "Additional cost from" : "From"} ${fromPrice}`}</span><small>{lowestPackagePrice === undefined ? service.isAddOn ? "Added to a suitable main service" : fromPrice === "POA" ? "Contact us for tailored pricing" : "Price varies by vehicle size" : <><strong>Package from £{lowestPackagePrice}</strong>Lowest package rate per visit</>}</small></div><a href="#sizes" className="button">Choose vehicle size <ArrowRight size={18} /></a></div><div className="service-hero-proof"><Star fill="currentColor" /><strong>5-star service-led care</strong><span>Professional indoor facilities in Norwich</span></div></div></section>
    <section className="about-service"><div className="shell about-grid"><div><p className="kicker">Service overview</p><h2>About {service.title}.</h2><p>{service.description}</p>{service.priceNote && <p className="service-requirement"><strong>{service.isAddOn ? "Booking requirement:" : "Important:"}</strong> {service.priceNote}</p>}</div><div className="included-card"><p className="kicker">Key points</p><h3>What this service covers</h3><ul>{service.includes.map((item) => <li key={item}><Check size={18} />{item}</li>)}</ul><p className="included-note">We inspect the vehicle first and tailor the process to its condition.</p></div></div></section>
    <section className="section shell" id="sizes"><div className="section-heading compact"><div><p className="kicker">Choose your vehicle</p><h2>{service.isAddOn ? "Additional service pricing." : category.slug === "valet-bay-hire" ? "One session. Fixed price." : "One service. Four sizes."}</h2></div><p>{service.isAddOn ? "These prices are added to the cost of a suitable main service. Select your vehicle size to see the additional charge." : category.slug === "valet-bay-hire" ? "Bay hire is priced by session length, so the same hire price applies to every vehicle-size option." : "Select your size when booking. We’ll confirm the correct category and final price before your appointment."}</p></div><div className="size-grid">{sizeOptions.map((size, index) => { const packagePrice = getLowestPackagePrice(service.slug, size.key); return <a href="#book" key={size.name} className="size-card"><div className="size-card-top"><span>0{index + 1}</span><span className={`size-vehicle-icon size-vehicle-icon--${index + 1}`} aria-hidden="true"><CarFront /></span></div><h3>{size.name}</h3><p>{size.example}</p><div className={`size-price${packagePrice === undefined ? "" : " size-price-options"}`}><div><span>{service.isAddOn ? "Additional cost" : "Single service"}</span><strong>{prices[size.key].display}</strong></div>{packagePrice !== undefined && <div><span>Package from</span><strong>£{packagePrice}<small> / visit</small></strong></div>}</div><span className="size-select">Select size <ArrowRight size={16} /></span></a>; })}</div>{service.priceNote && <p className="service-price-note"><strong>{service.isAddOn ? "Additional cost:" : "Pricing note:"}</strong> {service.priceNote}</p>}</section>
    {servicePackages.length > 0 && <section className="service-packages"><div className="shell"><div className="section-heading compact"><div><p className="kicker">Vehicle valeting packages</p><h2>Book once or choose regular care.</h2></div></div><div className="service-package-grid">{servicePackages.map((item) => { const packageSizes = (Object.keys(sizeLabels) as VehicleSize[]).filter(size => item.prices[size] !== undefined); const packageFrom = Math.min(...packageSizes.map(size => item.totals?.[size] ?? item.prices[size] as number)); const query = new URLSearchParams({ type: "valet", service: service.slug, package: item.crmSlug }); const [packageName, packageTerm] = item.name.split(" — "); return <article key={item.id}><div className="service-package-heading"><span>{item.term}</span><h3><span>{packageName}</span>{packageTerm && <small>— {packageTerm}</small>}</h3><p>{item.description}</p><div><strong>From £{packageFrom}</strong><small>{item.totals ? `package total · ${item.appointmentCount} visits` : "per appointment"}</small></div></div>{item.includes.length > 0 && <ul>{item.includes.map(point => <li key={point}><Check size={17} />{point}</li>)}</ul>}<div className="service-package-prices">{packageSizes.map(size => <div key={size}><span>{sizeLabels[size]}</span><strong>£{item.totals?.[size] ?? item.prices[size]}{item.totals ? " total" : ""}</strong></div>)}</div>{item.totals ? <a className="button" href={`?${query.toString()}#book`}>Choose package <ArrowRight size={17} /></a> : <Link className="button" href="/contact">Enquire about package <ArrowRight size={17} /></Link>}{item.note && <p className="service-package-note">{item.note}</p>}</article>; })}</div></div></section>}
    <section className="section shell gallery-section"><div className="section-heading compact"><div><p className="kicker">Recent work</p><h2>Care in the details.</h2></div></div><div className="gallery-grid"><div className="gallery-large"><img src={serviceImage} alt={serviceImageAlt} width="1200" height="800" loading="lazy" decoding="async" /></div><div className="gallery-tile dark-tile"><span>Clean</span><strong>Prepare</strong><span>Refine</span></div><div className="gallery-tile"><img src={category.slug === "vehicle-washing" ? "/images/categories/vehicle-valeting.webp" : "/images/categories/vehicle-washing.webp"} alt={`Supporting vehicle care for ${service.title} at Auto Opulence`} width="1200" height="800" loading="lazy" decoding="async" /></div></div></section>
    <section className="reviews-section"><div className="shell review-grid"><div><Quote /><p>“Really happy with the attention to detail. The car felt properly cared for from start to finish.”</p><span>Verified customer · Norwich</span></div><div><div className="stars">★★★★★</div><strong>Built around careful, consistent work</strong><p>Clear service choices, professional facilities and a final check before handover.</p></div></div></section>
    <section className="section shell faq-section"><div><p className="kicker">Frequently asked</p><h2>Good to know.</h2></div><div className="faq-list">{faqs.map((faq, index) => <details key={faq.question} open={index === 0}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</div></section>
    <section className="booking-section shell"><BookingWidget initialCategory={category.slug} initialService={service.slug} /></section>
    <section className="section shell related-section"><div className="section-heading compact"><div><p className="kicker">Related products</p><h2>Continue your vehicle care.</h2></div></div><div className="related-grid">{related.map((item) => <Link key={item.slug} href={`/service/${item.slug}`}><span>{category.title}</span><h3>{item.title}</h3><p>{item.short}</p><strong>View service <ArrowRight size={16} /></strong></Link>)}</div></section>
    {helpfulGuides.length > 0 && <section className="section shell service-guide-links"><div className="section-heading compact"><div><p className="kicker">Helpful advice</p><h2>Understand the treatment.</h2></div><p>Use these detailed guides to compare options, plan aftercare and decide whether this service fits the vehicle.</p></div><div>{helpfulGuides.map((guide) => <Link href={`/guides/${guide.slug}`} key={guide.slug}><img src={guide.heroImage} alt={guide.heroAlt} /><span>{guide.category} · {guide.readTime}</span><h3>{guide.name}</h3><strong>Read guide <ArrowRight size={16} /></strong></Link>)}</div></section>}
    <section className="service-links shell"><h2>Complete your vehicle-care plan</h2><p>For the best ongoing result, combine {service.title.toLowerCase()} with complementary Auto Opulence services. Explore {complementary.map((item, index) => <span key={item.slug}>{index > 0 && (index === complementary.length - 1 ? " or " : ", ")}<Link href={`/category/${item.slug}`}>{item.title.toLowerCase()} in Norwich</Link></span>)}. You can also check our <Link href="/locations">Norfolk service areas</Link>, <Link href="/business-sectors">business vehicle solutions</Link> and <Link href="/guides">vehicle-care guides</Link> before choosing.</p></section>
    <section className="contact-strip"><div className="shell"><div><p className="kicker">Not sure what to book?</p><h2>Talk it through with us.</h2></div><div><a href="tel:03300536925" className="button">Call 0330 053 6925</a><Link href="/contact" className="inline-link">Send an enquiry <ArrowRight size={17} /></Link></div></div></section>
  </main><Footer /></>;
}
