import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, Droplets, Gauge, Lightbulb, ShieldCheck, Snowflake, Sparkles, Wind } from "lucide-react";
import { Header, Footer } from "@/components/site-chrome";
import { JsonLd } from "@/components/json-ld";
import { categories } from "@/lib/services";
import { localBusinessSchema, siteUrl } from "@/lib/seo";

const title = "About Auto Opulence | Vehicle Care Specialists Norwich";
const description = "Discover Auto Opulence in Norwich, our professional vehicle valeting, washing, polishing, ceramic coating and equipped valet bay hire services.";

export const metadata: Metadata = {
  title,
  description,
  alternates: { canonical: "/about" },
  openGraph: { title, description, url: "/about", siteName: "Auto Opulence", locale: "en_GB", type: "website", images: [{ url: "/images/about/about-auto-opulence-norwich-hero.webp", width: 1200, height: 800, alt: "Professionally detailed Range Rover Sport inside the Auto Opulence Norwich studio" }] },
  twitter: { card: "summary_large_image", title, description, images: ["/images/about/about-auto-opulence-norwich-hero.webp"] },
};

const equipment = [
  { icon: Snowflake, title: "Climate-controlled indoor bay", text: "A sheltered working environment supports consistent cleaning, polishing and coating work throughout the year." },
  { icon: Droplets, title: "Wash floor and drainage", text: "Purpose-planned drainage allows controlled indoor washing without relying on unsuitable outdoor spaces." },
  { icon: Lightbulb, title: "Paint-inspection lighting", text: "A specialist lighting tunnel makes swirls, haze and polishing progress easier to assess accurately." },
  { icon: Gauge, title: "Kranzle K7 pressure washer", text: "Professional pressure-washing equipment supports thorough pre-washing, rinsing and wheel cleaning." },
  { icon: Sparkles, title: "Inline spotless water", text: "Filtered water helps reduce mineral spotting and supports a cleaner final rinse during vehicle preparation." },
  { icon: Wind, title: "Extraction and wet-vacuum equipment", text: "Interior cleaning equipment supports carpets, mats, upholstery and detailed cabin work where appropriate." },
];

export default function AboutPage() {
  const pageUrl = `${siteUrl}/about`;
  const heroImage = `${siteUrl}/images/about/about-auto-opulence-norwich-hero.webp`;
  const equipmentImage = `${siteUrl}/images/about/professional-valeting-equipment-norwich.webp`;
  const schema = { "@context": "https://schema.org", "@graph": [localBusinessSchema, { "@type": "AboutPage", "@id": `${pageUrl}/#webpage`, url: pageUrl, name: title, description, about: { "@id": `${siteUrl}/#business` }, mainEntity: { "@id": `${siteUrl}/#business` }, primaryImageOfPage: { "@id": `${pageUrl}/#primaryimage` }, associatedMedia: { "@id": `${pageUrl}/#equipment-image` }, inLanguage: "en-GB" }, { "@type": "ImageObject", "@id": `${pageUrl}/#primaryimage`, contentUrl: heroImage, caption: "Professionally detailed Range Rover Sport inside the Auto Opulence Norwich vehicle-care studio" }, { "@type": "ImageObject", "@id": `${pageUrl}/#equipment-image`, contentUrl: equipmentImage, caption: "Professional valeting and detailing equipment at Auto Opulence in Norwich" }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteUrl }, { "@type": "ListItem", position: 2, name: "About Auto Opulence", item: pageUrl }] }] };
  return <><JsonLd data={schema} /><Header /><main>
    <section className="about-hero about-hero--full"><img className="about-hero-background" src="/images/about/about-auto-opulence-norwich-hero.webp" alt="Professionally detailed right-hand-drive Range Rover Sport inside the Auto Opulence Norwich studio" /><div className="about-hero-shade" /><div className="shell about-hero-content"><p className="kicker">About Auto Opulence</p><h1>Professional care, properly equipped.</h1><p>Auto Opulence is a Norwich vehicle-care specialist built around careful methods, clear service choices and a purpose-equipped indoor facility.</p><div className="about-hero-actions"><Link href="/#book" className="button">Book a service <ArrowRight size={18} /></Link><Link href="/contact" className="inline-link">Contact the team</Link></div></div></section>
    <section className="section shell about-intro"><div><p className="kicker">What we do</p><h2>One place for everyday care and specialist detailing.</h2></div><div><p>Our service range covers the complete journey from routine vehicle cleaning to more involved paint correction and long-term ceramic protection. Each booking begins with the service required, the vehicle-size band and its present condition. This gives customers a clearer route to the right treatment and allows the working time to be planned properly.</p><p>Private customers can book washing, interior or exterior valeting, polishing and protection. Enthusiasts and automotive professionals can also <Link href="/category/valet-bay-hire">hire the equipped valet bay</Link> for their own work. Businesses can use our <Link href="/business-sectors">commercial vehicle-care routes</Link> for fleets, dealerships, taxis, lease returns, garages and bodyshops.</p></div></section>
    <section className="about-services"><div className="shell"><div className="section-heading compact"><div><p className="kicker">Core services</p><h2>Four specialist sectors.</h2></div><p>Choose a category to compare individual treatments, included work, vehicle sizes and booking options.</p></div><div className="about-service-grid">{categories.map((category) => <Link href={`/category/${category.slug}`} key={category.slug}><img src={category.image} alt={`${category.title} at Auto Opulence Norwich`} /><div><span>{category.eyebrow}</span><h3>{category.title}</h3><p>{category.intro}</p><strong>Explore services <ArrowRight size={17} /></strong></div></Link>)}</div></div></section>
    <section className="about-equipment" id="equipment"><div className="about-equipment-hero"><img src="/images/about/professional-valeting-equipment-norwich.webp" alt="Professional pressure washer, spotless-water system, wet vacuum and polishing equipment in the Auto Opulence Norwich studio" /><div className="about-equipment-shade" /><div className="shell"><p className="kicker">Professional equipment</p><h2>Built to support better work.</h2><p>The indoor facility combines washing, interior cleaning and paint-refinement equipment in one controlled workspace.</p></div></div><div className="section shell"><div className="equipment-grid">{equipment.map(({ icon: Icon, title: itemTitle, text }) => <article key={itemTitle}><Icon /><h3>{itemTitle}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="standards-section"><div className="shell standards-grid"><div><p className="kicker">Our approach</p><h2>Care planned around the vehicle.</h2><p>We do not treat every car as though it needs the same process. The safest useful result depends on how the vehicle is used, its materials, its existing protection and the condition of the paint or cabin.</p><Link href="/guides" className="inline-link">Read our vehicle-care guides <ArrowRight size={17} /></Link></div><ul><li><ShieldCheck /><span><strong>Condition-led recommendations</strong>Work is matched to what the vehicle genuinely needs.</span></li><li><Check /><span><strong>Surface-appropriate products</strong>Paint, trim, glass, fabrics and wheels receive suitable treatment.</span></li><li><Sparkles /><span><strong>Clear finishing checks</strong>Completed work is reviewed before vehicle handover.</span></li></ul></div></section>
    <section className="section shell about-work"><div className="section-heading compact"><div><p className="kicker">See the results</p><h2>Explore our work.</h2></div><p>Choose a category to see the treatments, pricing and real vehicle-care work most relevant to you.</p></div><div className="about-work-grid">{categories.map((category) => <Link href={`/category/${category.slug}`} key={category.slug}><figure><img src={category.image} alt={`${category.title} work completed by Auto Opulence in Norwich`} /></figure><div><span>{category.eyebrow}</span><h3>{category.title}</h3><p>{category.intro}</p><strong>Explore category <ArrowRight size={17} /></strong></div></Link>)}</div><div className="about-work-actions"><Link href="/gallery" className="inline-link">Browse the full gallery <ArrowRight size={17} /></Link><Link href="/case-studies" className="inline-link">Read customer case studies <ArrowRight size={17} /></Link></div></section>
  </main><Footer /></>;
}
