import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, Check, Clock3, MapPin, ShieldCheck, X } from "lucide-react";
import { Header, Footer } from "@/components/site-chrome";
import { JsonLd } from "@/components/json-ld";
import { sectors } from "@/lib/content";
import { localBusinessSchema, siteUrl } from "@/lib/seo";

const title = "Business Vehicle Valeting Norwich | Auto Opulence";
const description = "Fleet valeting, dealership preparation, taxi cleaning, lease-return care, garage support and trade detailing bay hire in Norwich and Norfolk.";
const heroImage = "/images/home-sections/indoor-detailing-facility.webp";
const heroAlt = "Auto Opulence indoor vehicle valeting and detailing facility for Norwich businesses";
const faqs = [
  { question: "Which businesses can use Auto Opulence vehicle-care services?", answer: "We provide suitable routes for company fleets, dealerships, taxi and private-hire drivers, lease-return customers, garages, bodyshops and professional detailers. Other commercial requirements can be discussed through the enquiry form." },
  { question: "Can several business vehicles use different services?", answer: "Yes. Services are matched to vehicle size, current condition and the required presentation standard, so a regularly maintained vehicle does not need to receive the same treatment as a heavily used or paint-damaged vehicle." },
  { question: "Are business vehicle-care prices published?", answer: "Individual service pages show confirmed size-based or session prices where applicable. Multi-vehicle, recurring or unusual requirements are reviewed before a quotation is confirmed." },
  { question: "Where is the work completed?", answer: "Auto Opulence operates from Unit 7 Consensus House, St Faiths Road, Norwich, Norfolk, NR6 7BW. Trade users can also book the professional indoor detailing bay for their own work." },
  { question: "How do we request repeat or multi-vehicle work?", answer: "Send the number and type of vehicles, current condition, required frequency, preferred dates and presentation standard. We aim to respond to enquiries within 24 hours." },
];

export const metadata: Metadata = {
  title,
  description,
  alternates: { canonical: "/business-sectors" },
  openGraph: { title, description, url: "/business-sectors", siteName: "Auto Opulence", locale: "en_GB", type: "website", images: [{ url: heroImage, width: 1200, height: 800, alt: heroAlt }] },
  twitter: { card: "summary_large_image", title, description, images: [heroImage] },
};

export default function BusinessSectorsPage() {
  const pageUrl = `${siteUrl}/business-sectors`;
  const schema = { "@context": "https://schema.org", "@graph": [localBusinessSchema, { "@type": "CollectionPage", "@id": `${pageUrl}/#webpage`, url: pageUrl, name: title, description, about: { "@id": `${siteUrl}/#business` }, mainEntity: { "@id": `${pageUrl}/#sectors` }, primaryImageOfPage: { "@id": `${pageUrl}/#primaryimage` }, inLanguage: "en-GB" }, { "@type": "ImageObject", "@id": `${pageUrl}/#primaryimage`, contentUrl: `${siteUrl}${heroImage}`, caption: heroAlt }, { "@type": "ItemList", "@id": `${pageUrl}/#sectors`, name: "Business vehicle-care sectors", numberOfItems: sectors.length, itemListElement: sectors.map((sector, index) => ({ "@type": "ListItem", position: index + 1, name: sector.name, url: `${siteUrl}/business-sectors/${sector.slug}` })) }, { "@type": "FAQPage", "@id": `${pageUrl}/#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteUrl }, { "@type": "ListItem", position: 2, name: "Business Sectors", item: pageUrl }] }] };
  return <><JsonLd data={schema} /><Header /><main>
    <section className="service-hero business-hub-hero"><img className="service-hero-image" src={heroImage} alt={heroAlt} /><div className="service-hero-shade" /><div className="shell service-hero-content"><div /><div className="service-hero-copy"><p className="kicker">Vehicle care for business · Norwich</p><h1>Commercial vehicle care shaped around the work.</h1><p>Choose a route for fleets, retail stock, passenger vehicles, lease returns, workshop support or professional detailing bay hire.</p><div className="business-hero-actions"><a href="#choose-sector" className="button">Choose your sector <ArrowRight size={18} /></a><Link href="/contact" className="business-hero-link">Make an enquiry</Link></div></div><div className="service-hero-proof business-hero-proof"><BriefcaseBusiness /><strong>{sectors.length} focused business routes</strong><span>Norwich facility · Norfolk service area</span></div></div></section>

    <section className="section shell business-hub-intro"><div><p className="kicker">A clearer commercial starting point</p><h2>Match the service to the vehicle and objective.</h2></div><div><p>A customer-facing company car, used dealership stock and a high-mileage private-hire vehicle do not need the same process. These sector guides connect common operational requirements to relevant washing, valeting, polishing and bay-hire services.</p><p>Every detailed page explains the likely challenges, recommended treatments, published starting prices, facilities, working process and questions to consider before requesting a quotation.</p></div></section>

    <section className="business-hub-sectors" id="choose-sector"><div className="section shell"><div className="section-heading compact"><div><p className="kicker">Choose your sector</p><h2>Six practical business routes.</h2></div><p>Open the sector closest to your requirement. If the business does not fit neatly into one option, send the vehicle details and intended result for an individual recommendation.</p></div><div className="business-sector-card-grid">{sectors.map((sector) => <article className="business-sector-card" key={sector.slug}><Link href={`/business-sectors/${sector.slug}`} className="business-sector-card-image"><img src={sector.heroImage} alt={sector.heroAlt} /><span>Business vehicle care</span></Link><div><h3><Link href={`/business-sectors/${sector.slug}`}>{sector.name}</Link></h3><p>{sector.intro}</p><ul>{sector.solutions.slice(0, 3).map((solution) => <li key={solution}><Check size={15} />{solution}</li>)}</ul><Link href={`/business-sectors/${sector.slug}`} className="business-sector-card-link">Explore {sector.name.toLowerCase()} <ArrowRight size={17} /></Link></div></article>)}</div></div></section>

    <section className="section shell business-sector-matrix"><div className="section-heading compact"><div><p className="kicker">Compare the focus</p><h2>Which route fits the requirement?</h2></div><p>The grid highlights the main emphasis of each sector page. Individual vehicles are still inspected before a treatment is confirmed.</p></div><div className="business-matrix-wrap"><table><thead><tr><th>Business sector</th><th>Repeat care</th><th>Interior focus</th><th>Paint enhancement</th><th>Trade bay hire</th></tr></thead><tbody>{sectors.map((sector) => <tr key={sector.slug}><th scope="row"><Link href={`/business-sectors/${sector.slug}`}>{sector.name}<ArrowRight size={15} /></Link></th>{(["repeat", "interior", "paint", "bay"] as const).map((key) => <td key={key}>{sector.matrix[key] ? <span className="matrix-yes"><Check /><span className="sr-only">Relevant</span></span> : <span className="matrix-no"><X /><span className="sr-only">Not a primary focus</span></span>}</td>)}</tr>)}</tbody></table></div></section>

    <section className="business-hub-benefits"><div className="section shell"><div className="section-heading compact"><div><p className="kicker">Why Auto Opulence</p><h2>Professional facilities. Clear choices.</h2></div></div><div className="business-benefit-grid"><article><ShieldCheck /><h3>Condition-led recommendations</h3><p>Services are selected from vehicle size, use and actual condition rather than automatically placing every business vehicle into the same package.</p></article><article><BriefcaseBusiness /><h3>Indoor professional facility</h3><p>Washing, interior care, paint inspection, polishing and trade hire are supported by a purpose-equipped Norwich workspace.</p></article><article><Clock3 /><h3>Planned working time</h3><p>Expected timing and access requirements are discussed before the appointment, helping businesses plan vehicle downtime more clearly.</p></article></div></div></section>

    <section className="section shell business-local business-hub-local"><div><p className="kicker">Norwich and Norfolk</p><h2>One confirmed business address.</h2><p>Auto Opulence operates from Unit 7 Consensus House, St Faiths Road, Norwich, NR6 7BW. Our location guides provide journey and appointment guidance for businesses travelling from across Norfolk.</p><Link href="/locations" className="inline-link">Explore all service areas <ArrowRight size={17} /></Link></div><nav aria-label="Popular business vehicle-care locations"><Link href="/locations/norwich"><MapPin /><span><strong>Norwich</strong>Local facility guide</span><ArrowRight size={16} /></Link><Link href="/locations/wymondham"><MapPin /><span><strong>Wymondham</strong>Route and service guide</span><ArrowRight size={16} /></Link><Link href="/locations/dereham"><MapPin /><span><strong>Dereham</strong>Route and service guide</span><ArrowRight size={16} /></Link></nav></section>

    <section className="section shell faq-section"><div><p className="kicker">Business vehicle FAQs</p><h2>Before making an enquiry.</h2></div><div className="faq-list">{faqs.map((faq, index) => <details key={faq.question} open={index === 0}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</div></section>

    <section className="support-band"><div className="shell support-band-grid"><div><p className="kicker">Need a tailored arrangement?</p><h2>Discuss vehicles, frequency and access.</h2><p>Tell us the vehicle numbers, sizes, condition, required presentation standard, preferred dates and whether the work is one-off or recurring.</p></div><div><Link href="/contact" className="button">Make a business enquiry <ArrowRight size={17} /></Link></div></div></section>
  </main><Footer /></>;
}
